### ISSUE TITLE
Error when setting up the workspace: `You are in 'detached HEAD' state.`

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino_product#2]
* Release number or git hash: master
* Web browser version and OS: Windows (tested by me) and Linux (tested by @anita-steiner)
* Environment (local or deployed): local

### Steps to reproduce

1. Open CMD
2. `yo phovea:setup-workspace ordino_product`

### Observed behavior
```
? SSH clone No
create directory: ordino
clone repository: git clone -b master --depth 1 https://github.com/Caleydo/ordino_product.git
Cloning into 'ordino_product'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 16 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
clone repository: git clone -b v3.1.0 https://github.com/Caleydo/ordino_public.git
Cloning into 'ordino_public'...
remote: Counting objects: 360, done.
remote: Compressing objects: 100% (12/12), done.
Receiving objects:  93% (335/360)   12 (delta 5), pack-reused 343 eceiving objects:  89% (321/360)
Receiving objects: 100% (360/360), 147.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (193/193), done.
Note: checking out 'c93e62cfc7b330470a429a5c652609ba6715842b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

clone repository: git clone -b v3.1.0 https://github.com/Caleydo/tdp_gene.git
Cloning into 'tdp_gene'...
remote: Counting objects: 2480, done.
remote: Compressing objects: 100% (10/10), done.
Receiving objects: 100% (2480/2480), 566.99 KiB | 0 bytes/s, done.0eceiving objects:  61% (1513/2480)
Resolving deltas: 100% (1736/1736), done.

Note: checking out '5df9bd96dc3c6b937aacd2c7ffbd57cb40621bb9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

[94mclone repository:[39m git clone -b v3.1.0 https://github.com/Caleydo/tdp_publicdb.git
Cloning into 'tdp_publicdb'...
remote: Counting objects: 3579, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 3579 (delta 4), reused 4 (delta 1), pack-reused 3563
Receiving objects: 100% (3579/3579), 2.00 MiB | 847.00 KiB/s, done.
Resolving deltas: 100% (2486/2486), done.
Note: checking out 'bd6dbc1c1b248b0d6bc9dd8157162e58688a329e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

[94mclone repository:[39m git clone -b v3.1.0 https://github.com/datavisyn/tdp_uploaded_data.git
Cloning into 'tdp_uploaded_data'...
remote: Repository not found.
fatal: repository 'https://github.com/datavisyn/tdp_uploaded_data.git/' not found
{ status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 19348,
  stdout: null,
  stderr: null,
  envPairs:
   [ 'ALLUSERSPROFILE=C:\\ProgramData',
     'APPDATA=C:\\Users\\Holger Stitz\\AppData\\Roaming',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=DESKTOP-0DE31SV',
     'ComSpec=C:\\WINDOWS\\system32\\cmd.exe',
     'DEFLOGDIR=C:\\ProgramData\\McAfee\\DesktopProtection',
     'FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer',
     'FPS_BROWSER_USER_PROFILE_STRING=Default',
     'GIT_LFS_PATH=C:\\Program Files\\Git LFS',
     'GYP_MSVS_VERSION=2015',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\Holger Stitz',
     'LOCALAPPDATA=C:\\Users\\Holger Stitz\\AppData\\Local',
     'LOGONSERVER=\\\\DESKTOP-0DE31SV',
     'NUMBER_OF_PROCESSORS=4',
     'OneDrive=C:\\Users\\Holger Stitz\\OneDrive',
     'OS=Windows_NT',
     'Path=C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\HashiCorp\\Vagrant\\bin;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\PostgreSQL\\9.5\\bin;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;D:\\Users\\Holger Stitz\\Downloads\\programme\\ffmpeg-20161204-1f5630a-win64-static\\bin\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\Amazon\\AWSCLI\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git LFS;C:\\Users\\Holger Stitz\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Holger Stitz\\AppData\\Local\\atom\\bin;C:\\Users\\Holger Stitz\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Holger Stitz\\AppData\\Roaming\\npm;C:\\Users\\Holger Stitz\\AppData\\Local\\rodeo\\app-2.5.2\\bin;C:\\Program Files\\Microsoft VS Code\\bin',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.CPL',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=3c03',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PROMPT=$P$G',
     'PSModulePath=D:\\Users\\Holger Stitz\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
     'PUBLIC=C:\\Users\\Public',
     'SESSIONNAME=Console',
     'SystemDrive=C:',
     'SystemRoot=C:\\WINDOWS',
     'TEMP=C:\\Users\\HOLGER~1\\AppData\\Local\\Temp',
     'TMP=C:\\Users\\HOLGER~1\\AppData\\Local\\Temp',
     'USERDOMAIN=DESKTOP-0DE31SV',
     'USERDOMAIN_ROAMINGPROFILE=DESKTOP-0DE31SV',
     'USERNAME=Holger Stitz',
     'USERPROFILE=C:\\Users\\Holger Stitz',
     'VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
     'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
     'VSEDEFLOGDIR=C:\\ProgramData\\McAfee\\DesktopProtection',
     'windir=C:\\WINDOWS' ],
  options:
   { cwd: 'ordino',
     stdio: [ [Object], [Object], [Object] ],
     file: 'git',
     args:
      [ 'git',
        'clone',
        '-b',
        'v3.1.0',
        'https://github.com/datavisyn/tdp_uploaded_data.git' ],
     envPairs:
      [ 'ALLUSERSPROFILE=C:\\ProgramData',
        'APPDATA=C:\\Users\\Holger Stitz\\AppData\\Roaming',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=DESKTOP-0DE31SV',
        'ComSpec=C:\\WINDOWS\\system32\\cmd.exe',
        'DEFLOGDIR=C:\\ProgramData\\McAfee\\DesktopProtection',
        'FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING=Default',
        'GIT_LFS_PATH=C:\\Program Files\\Git LFS',
        'GYP_MSVS_VERSION=2015',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\Holger Stitz',
        'LOCALAPPDATA=C:\\Users\\Holger Stitz\\AppData\\Local',
        'LOGONSERVER=\\\\DESKTOP-0DE31SV',
        'NUMBER_OF_PROCESSORS=4',
        'OneDrive=C:\\Users\\Holger Stitz\\OneDrive',
        'OS=Windows_NT',
        'Path=C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\HashiCorp\\Vagrant\\bin;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\PostgreSQL\\9.5\\bin;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;D:\\Users\\Holger Stitz\\Downloads\\programme\\ffmpeg-20161204-1f5630a-win64-static\\bin\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\Amazon\\AWSCLI\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git LFS;C:\\Users\\Holger Stitz\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Holger Stitz\\AppData\\Local\\atom\\bin;C:\\Users\\Holger Stitz\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Holger Stitz\\AppData\\Roaming\\npm;C:\\Users\\Holger Stitz\\AppData\\Local\\rodeo\\app-2.5.2\\bin;C:\\Program Files\\Microsoft VS Code\\bin',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.CPL',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=3c03',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PROMPT=$P$G',
        'PSModulePath=D:\\Users\\Holger Stitz\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC=C:\\Users\\Public',
        'SESSIONNAME=Console',
        'SystemDrive=C:',
        'SystemRoot=C:\\WINDOWS',
        'TEMP=C:\\Users\\HOLGER~1\\AppData\\Local\\Temp',
        'TMP=C:\\Users\\HOLGER~1\\AppData\\Local\\Temp',
        'USERDOMAIN=DESKTOP-0DE31SV',
        'USERDOMAIN_ROAMINGPROFILE=DESKTOP-0DE31SV',
        'USERNAME=Holger Stitz',
        'USERPROFILE=C:\\Users\\Holger Stitz',
        'VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
        'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
        'VSEDEFLOGDIR=C:\\ProgramData\\McAfee\\DesktopProtection',
        'windir=C:\\WINDOWS' ] },
  args:
   [ 'git',
     'clone',
     '-b',
     'v3.1.0',
     'https://github.com/datavisyn/tdp_uploaded_data.git' ],
  file: 'git',
  error: null }
[94mclone repository:[39m git clone -b develop https://github.com/phovea/phovea_server.git
Cloning into 'phovea_server'...
remote: Counting objects: 2073, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2073 (delta 2), reused 2 (delta 0), pack-reused 2066R
Receiving objects: 100% (2073/2073), 407.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1386/1386), done.
[94mclone repository:[39m git clone -b develop https://github.com/phovea/phovea_security_flask.git
Cloning into 'phovea_security_flask'...
remote: Counting objects: 477, done.
Rremote: Total 477 (delta 0), reused 0 (delta 0), pack-reused 477                     % (363/477)
Receiving objects: 100% (477/477), 85.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (282/282), done.
[94mclone repository:[39m git clone -b develop https://github.com/phovea/phovea_data_redis.git
Cloning into 'phovea_data_redis'...
remote: Counting objects: 444, done.
Rremote: Total 444 (delta 0), reused 0 (delta 0), pack-reused 444
Receiving objects: 100% (444/444), 64.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (258/258), done.
[94mclone repository:[39m git clone -b develop https://github.com/phovea/phovea_data_mongo.git
Cloning into 'phovea_data_mongo'...
remote: Counting objects: 352, done.
Rremote: Total 352 (delta 0), reused 0 (delta 0), pack-reused 352                     % (222/352)
Receiving objects: 100% (352/352), 55.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (186/186), done.
[94mclone repository:[39m git clone -b develop https://github.com/phovea/phovea_clue.git
Cloning into 'phovea_clue'...
remote: Counting objects: 3823, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 3823 (delta 5), reused 10 (delta 3), pack-reused 3808
Receiving objects: 100% (3823/3823), 920.68 KiB | 808.00 KiB/s, done.
Resolving deltas: 100% (2721/2721), done.
[94mclone repository:[39m git clone -b v3.1.0 https://github.com/datavisyn/tdp_core.git
Cloning into 'tdp_core'...
remote: Counting objects: 6783, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 6783 (delta 54), reused 53 (delta 25), pack-reused 6690
Receiving objects: 100% (6783/6783), 1.06 MiB | 808.00 KiB/s, done.
Resolving deltas: 100% (4972/4972), done.
Note: checking out 'a542a20538d1a4991a67c0bbe53c497e3f921fa6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

[31mError: failed: git - status code: 128[39m
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (failed: git - status code: 128)
    at Generator.emit (events.js:163:17)
    at Immediate.<anonymous> (D:\dev\repos\phovea\generator-phovea\node_modules\yeoman-generator\lib\base.js:446:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Expected behavior
* The setup should finish without errors.

**Comment by sgratzl** [comment]
checking out tags results in detached heads -> normal. And for the other error, you don't have the rights by default for this specific plugin.

**Comment by thinkh** [comment]
Additionally, running `yo phovea:setup-workspace ordino_product -b develop` terminates with the in the following error log:

```
clone repository:[39m git clone -b develop https://github.com/datavisyn/tdp_core.git
Cloning into 'tdp_core'...
remote: Counting objects: 6783, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 6783 (delta 54), reused 53 (delta 25), pack-reused 6690
Receiving objects: 100% (6783/6783), 1.06 MiB | 733.00 KiB/s, done.
Resolving deltas: 100% (4972/4972), done.
[31mError: failed: git - status code: 128[39m
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (failed: git - status code: 128)
    at Generator.emit (events.js:163:17)
    at Immediate.<anonymous> (D:\dev\repos\phovea\generator-phovea\node_modules\yeoman-generator\lib\base.js:446:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by thinkh** [comment]
@sgratzl Thanks for the explanation. Can you please have a look on the termination error.

**Comment by sgratzl** [comment]
imo this is still the error that you don't have the right to clone a specific repository, it just falls through the different stages, since all repos are cloned at once using Promise.all

**Comment by thinkh** [comment]
@sgratzl Ok, thanks.
@anita-steiner I assume that all repos (except the tdp_uploaded_data) are cloned. So you can continue the setup after the error manually with: 
```
cd ordino
docker-compose up
npm install
```
I will close the ticket for now. If you have any further issue, you can re-open it again.

**Comment by keckelt** [comment]
Due to the error, the workspace isn't setup, so:

```
cd ordino
yo phovea:workspace
docker-compose up
npm install
```
