### ISSUE TITLE
Remove tdp_uploaded_data from product

### ISSUE THREAD

**Issue by keckelt** [Caleydo/ordino_product#3]
I don't know who has access to datavisyn/tdp_uploaded_data, but i think we should remove it from this (Caleydo) repo  and probably make a second (private) repo in datavisyn's organiztaion as it breaks the workspace setup.

**Comment by keckelt** [comment]
Error:
```
Error: failed: "git clone -b v4.0.1 git@github.com:datavisyn/tdp_uploaded_data.git" - status code: 128
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (failed: "git clone -b v4.0.1 git@github.com:datavisyn/tdp_uploaded_data.git" - status code: 128)
    at Generator.emit (events.js:171:17)
    at Immediate.<anonymous> (/home/klaus/.npm-global/lib/node_modules/generator-phovea/node_modules/yeoman-generator/lib/base.js:446:16)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)

```

**Comment by sgratzl** [comment]
caleydo-bot has access. That's why an `open-source´ branch exists in this repo which doesn't include it
